---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: abeventbot.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-f03d689e
  image_type: t1.micro
  image_id: ami-aecd60c7
  security_groups:
  - ab_event_bot_production_default
  - ab_event_bot_production_web
  - ab_event_bot_production_web_tools
  - ab_event_bot_production_production
  - ab_event_bot_production_examples
  - ab_event_bot_production_nginx
  - ab_event_bot_production_unicorn
  - ab_event_bot_production_db
  external_host: ec2-184-73-54-242.compute-1.amazonaws.com
  external_ip: 184.73.54.242
  internal_host: ip-10-164-116-149.ec2.internal
  internal_ip: 10.164.116.149
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
