---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: abeventbot.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-c0c7dea3
  image_type: m1.small
  image_id: ami-b6089bdf
  security_groups:
  - ab_event_bot_production_default
  - ab_event_bot_production_web
  - ab_event_bot_production_web_tools
  - ab_event_bot_production_production
  - ab_event_bot_production_examples
  - ab_event_bot_production_nginx
  - ab_event_bot_production_unicorn
  - ab_event_bot_production_db
  external_host: ec2-54-234-243-218.compute-1.amazonaws.com
  external_ip: 54.234.243.218
  internal_host: ip-10-158-39-185.ec2.internal
  internal_ip: 10.158.39.185
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
